# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('meinberlin', '0002_create_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='current_processes_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info1_text',
            field=models.CharField(blank=True, max_length=2047),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info1_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info2_text',
            field=models.CharField(blank=True, max_length=2047),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info2_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info3_text',
            field=models.CharField(blank=True, max_length=2047),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info3_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='netiquette_linktext',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='past_processes_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='privacy_linktext',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='processes_linktext',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='view_all',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
