# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin', '0003_auto_20160311_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocracyprocess',
            name='process_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adhocracyprocess',
            name='embed_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='process',
            name='image_copyright',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
