# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin', '0006_auto_20160323_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocracyprocess',
            name='process_type',
            field=models.CharField(choices=[('adhocracy_meinberlin.resources.alexanderplatz.IProcess', 'Alexanderplatz'), ('adhocracy_meinberlin.resources.bplan.IProcess', 'Bebauungsplan'), ('adhocracy_meinberlin.resources.burgerhaushalt.IProcess', 'Bürgerhaushalt'), ('adhocracy_meinberlin.resources.stadtforum.IPoll', 'Dialog'), ('adhocracy_meinberlin.resources.kiezkassen.IProcess', 'Kiezkasse'), ('adhocracy_meinberlin.resources.collaborative_text.IProcess', 'Kollaborative Textarbeit')], default='adhocracy_meinberlin.resources.kiezkassen.IProcess', max_length=255),
        ),
    ]
