# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin', '0008_alter_beteiligungsverfahren_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocracyprocess',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='adhocracyprocess',
            name='embed_url',
            field=models.URLField(unique=True, verbose_name='Embed-URL'),
        ),
        migrations.AlterField(
            model_name='adhocracyprocess',
            name='process_type',
            field=models.CharField(choices=[('adhocracy_meinberlin.resources.alexanderplatz.IProcess', 'Alexanderplatz'), ('adhocracy_meinberlin.resources.bplan.IProcess', 'Bebauungsplan'), ('adhocracy_meinberlin.resources.burgerhaushalt.IProcess', 'Bürgerhaushalt'), ('adhocracy_core.resources.proposal.IProposalVersion', 'Dialog'), ('adhocracy_meinberlin.resources.kiezkassen.IProcess', 'Kiezkasse'), ('adhocracy_meinberlin.resources.collaborative_text.IProcess', 'Kollaborative Textarbeit')], default='adhocracy_meinberlin.resources.kiezkassen.IProcess', max_length=255, verbose_name='Verfahrenstyp'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='external_url',
            field=models.URLField(unique=True, verbose_name='externe URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Titelbild'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='current_processes_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Aktuelle Verfahren Titel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kopfzeile'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info1_text',
            field=models.CharField(blank=True, max_length=2047, verbose_name='Infobox 1 Text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info1_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Infobox 1 Titel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info2_text',
            field=models.CharField(blank=True, max_length=2047, verbose_name='Infobox 2 Text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info2_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Infobox 2 Titel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info3_text',
            field=models.CharField(blank=True, max_length=2047, verbose_name='Infobox 3 Text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info3_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Infobox 3 Titel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='past_processes_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vergangene Verfahren Titel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='privacy_linktext',
            field=models.CharField(blank=True, max_length=255, verbose_name='Datenschutz Linktext'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='processes_linktext',
            field=models.CharField(blank=True, max_length=255, verbose_name='Verfahrensübersicht Linktext'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='view_all',
            field=models.CharField(blank=True, max_length=255, verbose_name='alle anzeigen'),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='process',
            name='archived',
            field=models.BooleanField(verbose_name='vergangen'),
        ),
        migrations.AlterField(
            model_name='process',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='process',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='process',
            name='image_copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='Urheberrecht'),
        ),
        migrations.AlterField(
            model_name='process',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Inhalt'),
        ),
    ]
