# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin', '0009_auto_20160504_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='archived',
            field=models.BooleanField(verbose_name='archiviert'),
        ),
        migrations.AlterField(
            model_name='process',
            name='image_copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bild Urheberrecht'),
        ),
    ]
