# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin', '0011_auto_20160601_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprocess',
            name='is_adhocracy',
            field=models.BooleanField(default=False, verbose_name='Wurde der externe Prozess mit Adhocracy umgesetzt?'),
        ),
    ]
