# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin', '0012_externalprocess_is_adhocracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocracyprocess',
            name='process_type',
            field=models.CharField(choices=[('adhocracy_meinberlin.resources.alexanderplatz.IProcess', 'Alexanderplatz'), ('adhocracy_meinberlin.resources.bplan.IProcess', 'Bebauungsplan'), ('adhocracy_meinberlin.resources.burgerhaushalt.IProcess', 'Bürgerhaushalt'), ('adhocracy_meinberlin.resources.collaborative_text.IProcess', 'Kollaborative Textarbeit'), ('adhocracy_core.resources.proposal.IProposalVersion', 'Dialog'), ('adhocracy_meinberlin.resources.stadtforum.IProcess', 'Dialogsammlung'), ('adhocracy_meinberlin.resources.idea_collection.IProcess', 'Idea Collection'), ('adhocracy_meinberlin.resources.kiezkassen.IProcess', 'Kiezkasse')], default='adhocracy_meinberlin.resources.kiezkassen.IProcess', max_length=255, verbose_name='Verfahrenstyp'),
        ),
    ]
